### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by hamana-n** [hamana-n/furima-35836#10]
Web URL|
https://furima-35836.herokuapp.com/

Basic認証のIDとパスワード|
admin     2222

出品者用のメールアドレスとパスワード |
メアド
furima@1
パス
furima1

購入者用のメールアドレスとパスワード |
メアド
furima@2
パス
furima2

**Comment by snkw-works** [comment]
@hamana-n さん、お待たせいたしました。ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下、ご確認をお願いします！

[修正依頼箇所]
- [ ] **商品の価格は、¥300~¥9,999,999の間のみ保存可能であるよう修正しましょう**
「10000000円」でも保存ができてしまう状態です。

- [ ] **ログイン状態且つ、自身が出品した販売中商品の場合にのみ、「商品の編集」「削除」ボタンが表示されるよう修正しましょう**
自身が出品した販売中商品の場合であっても、「商品の編集」「削除」ボタンが表示されない状態です。

- [ ] **ログイン状態且つ、自身が出品していない販売中商品の場合にのみ、「購入画面に進む」ボタンが表示されるよう修正しましょう**
自身が出品していない販売中商品の場合であっても、「購入画面に進む」ボタンが表示されない状態です。

- [ ] **ログイン状態の場合にのみ、自身が出品した商品情報を削除できるようにしましょう**
「削除」ボタンが表示されていないため、確認ができておりません。

※削除機能、購入機能、購入後に関する項目については動作確認ができていない為、次回ご提出時に併せて確認させていただきます。


修正が完了しましたら、再度以下の最終課題完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by takumi0530** [comment]
@hamana-n さん、再度ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

### **[修正依頼箇所]**

- [ ] **ログイン状態の場合でも、自身が出品していない商品の商品情報編集ページへ遷移しようとすると、商品の販売状況に関わらずトップページに遷移すること**
売却済の商品に対して商品情報編集ページへ遷移しようとすると、エラーページに遷移してしまいます。
<img width="621" alt="スクリーンショット 2021-09-10 15 11 37" src="https://user-images.githubusercontent.com/76197191/132808365-215cc6bf-29c1-42d5-a3d6-f8f1bb0e0e85.png">


修正が完了しましたら、再度以下の最終課題完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by mo1015** [comment]
ご提出ありがとうございます！お待たせいたしました。
問題なく正常に動作することが確認できました！LGTMです！　
おめでとうございます🎉


**※確認したのは必須機能のみです。追加実装した機能については確認しておりません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるか、再度ご自身でご確認をお願い致します。**
![最終課題終了_おめでとう画像2](https://user-images.githubusercontent.com/62644781/133009162-6463aec9-d98d-4009-83af-08d32129e325.png)

**Comment by hamana-n** [comment]
LGTM
